[package]
name = "esp-vindriktning"
version = "0.1.0"
authors = ["Tom치코 Vojt치코ek <vojtasek.tomas@gmail.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "z" # "s" is currently broken

[package.metadata.espflash]
partition_table = "partitions.csv" # Supports CSV and binary formats

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["experimental"]
experimental = ["esp-idf-svc/experimental", "embedded-svc/experimental"]

[dependencies]
esp-idf-sys = { version = "0.31.11", features = ["binstart"] }
log = "0.4.17"
esp-idf-svc = "0.43.4"
esp-idf-hal = "0.39.3"
embedded-svc= "0.23.1"
embedded-hal = "0.2.7"
anyhow = { version = "1", features = ["backtrace"] }
scd4x = "0.2.1"
ws2812-esp32-rmt-driver = "0.4.0"
smart-leds-trait = "0.2.1"
serde = "1.0.147"
serde_json = "1.0.88"

[build-dependencies]
embuild = "0.30.4"
anyhow = "1"
dotenv-build = "0.1.1"
