[package]
name = "esp-vindriktning"
version = "0.1.0"
authors = ["Tomáš Vojtášek <vojtasek.tomas@gmail.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "z" # "s" is currently broken

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
# default = ["experimental"]
# experimental = ["esp-idf-svc/experimental", "embedded-svc/experimental"]
# default = ["std",  "esp-idf-svc/native"]
# std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
# alloc = ["esp-idf-svc/alloc"]
# experimental = ["esp-idf-svc/experimental", "embedded-svc/experimental"]

[dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
embedded-hal = "1.0.0"
embedded-io = "0.7.1"
embedded-svc = "0.29.0"
esp-idf-svc = "0.52.1"
log = "0.4.34"
scd4x = { version = "0.5.0", features = ["scd41"] }
serde = "1.0.229"
serde_json = "1.0.151"
smart-leds-trait = "0.3.2"
sntp_request = "2.0.1"
pm1006 = "0.0.4"
time = "0.3.55"
time-tz = { version = "2.0.0", features = ["db"] }
ws2812-esp32-rmt-driver = { version = "0.14.0", features = ["smart-leds-trait"] }

[build-dependencies]
dotenv-build = "0.1.1"
embuild = "0.33.5"
