[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "espflash flash --monitor"
rustflags = [
    # "--cfg", "esp_idf_httpd_ws_support",
    "--cfg", "espidf_time64" # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
    ] 

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
ESP_IDF_VERSION = "v5.1.1"
